spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aamzerin/config-repo.git
  profiles:
    active:
    - localzone
      
server:
  port: 8889
      
      